http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - "ryan:$apr1$uSzn5oSf$NrjPhjAmYzSNrRHxfZU5c/" 
  routers:
    consul:
      rule: "Host(`consul-lab.clouddesigndev.com`)"
      service: "consul"
      tls:
        certResolver: le
  services:
    consul:
      loadBalancer:
        servers:
        - url: "http://10.245.64.4:8500"
        - url: "http://10.245.64.6:8500"
        - url: "http://10.245.64.5:8500"


    
      


